### ISSUE TITLE
Trailing slashes are being removed automatically

### ISSUE THREAD

**Issue by snugarchive** [TryGhost/gatsby-plugin-advanced-sitemap#223]
Trailing slashes are removed when generating a sitemap. This does not happen with the gatsby-plugin-sitemap. Got any ideas to fix this?

**Comment by robmarshall** [comment]
@snugarchive What was the outcome for this? I am having the same issue across my sites.

**Comment by snugarchive** [comment]
> @snugarchive What was the outcome for this? I am having the same issue across my sites.

I switched back to gatsby-plugin-sitemap. I added the "trailingSlash: 'always'" option in gatsby-config.js and works fine.

**Comment by wheredannyends** [comment]
For future reference, I was having this issue and resolved it by downgrading from `2.1.0` to `2.0.0`

**Comment by ezracelli** [comment]
For reference, the removal is happening here: https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/2350a96113e202511cd4157021503d7173e3acb2/src/gatsby-node.js#L86

Fairly easy to patch out, but I think this issue should be re-opened. [The behavior for a trailing slash mismatch depends entirely on the hosting provider](https://www.zachleat.com/web/trailing-slash/#results-table); some return the page content, some return 301s, and some return 404s. This has SEO implications, which should be extremely relevant to a sitemap generator. From https://github.com/facebook/docusaurus/issues/4134:

> Urls in sitemap.xml are currently listed without a trailing slash (i.e. ./blog instead of ./blog/), while, when going to the page, it redirects to the url with a trailing slash (i.e ./blog redirects to ./blog/)
> 
> [A 301 redirect] results in google indexing the page with a "redirect error".

Gatsby discussion on trailing slashes here: https://github.com/gatsbyjs/gatsby/discussions/34205

`@docusaurus/plugin-sitemap` solves this by adding a `trailingSlash` option, but we may not need that here; Gatsby has its own [`trailingSlash` option](https://www.gatsbyjs.com/docs/reference/release-notes/v4.7/#trailingslash-option) since v4.7, and older versions of Gatsby may use [gatsby-plugin-force-trailing-slashes](https://www.gatsbyjs.com/plugins/gatsby-plugin-force-trailing-slashes/) or [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-trailing-slashes/). However, it still might be beneficial to to have our own, independent option specific to this plugin for sitemap-specific trailing slash config.

Happy to submit a PR, if y'all are interested!

**Comment by FredWahlqvistSciart** [comment]
> For reference, the removal is happening here:
> 
> https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/2350a96113e202511cd4157021503d7173e3acb2/src/gatsby-node.js#L86
> 
> Fairly easy to patch out, but I think this issue should be re-opened. [The behavior for a trailing slash mismatch depends entirely on the hosting provider](https://www.zachleat.com/web/trailing-slash/#results-table); some return the page content, some return 301s, and some return 404s. This has SEO implications, which should be extremely relevant to a sitemap generator. From [facebook/docusaurus#4134](https://github.com/facebook/docusaurus/issues/4134):
> 
> > Urls in sitemap.xml are currently listed without a trailing slash (i.e. ./blog instead of ./blog/), while, when going to the page, it redirects to the url with a trailing slash (i.e ./blog redirects to ./blog/)
> > [A 301 redirect] results in google indexing the page with a "redirect error".
> 
> Gatsby discussion on trailing slashes here: [gatsbyjs/gatsby#34205](https://github.com/gatsbyjs/gatsby/discussions/34205)
> 
> `@docusaurus/plugin-sitemap` solves this by adding a `trailingSlash` option, but we may not need that here; Gatsby has its own [`trailingSlash` option](https://www.gatsbyjs.com/docs/reference/release-notes/v4.7/#trailingslash-option) since v4.7, and older versions of Gatsby may use [gatsby-plugin-force-trailing-slashes](https://www.gatsbyjs.com/plugins/gatsby-plugin-force-trailing-slashes/) or [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-trailing-slashes/). However, it still might be beneficial to to have our own, independent option specific to this plugin for sitemap-specific trailing slash config.
> 
> Happy to submit a PR, if y'all are interested!

Any progress on the PR?

**Comment by ezracelli** [comment]
@FredWahlqvistSciart No PR since I never heard back from the maintainers regarding interest.

I used `yarn patch` (yarn berry) to remove the offending bit, same could be accomplished with e.g. `pnpm patch` or `patch-package`
